insert into examples (text) values ('ligula vehicula consequat morbi a ipsum integer a nibh in');
insert into examples (text) values ('nisi at nibh in hac habitasse platea dictumst');
insert into examples (text) values ('amet nulla quisque arcu libero rutrum ac');
insert into examples (text) values ('ac est lacinia nisi venenatis tristique fusce congue diam');
insert into examples (text) values ('sapien dignissim vestibulum vestibulum ante ipsum');
insert into examples (text) values ('dapibus augue vel accumsan tellus nisi eu');
insert into examples (text) values ('tincidunt in leo maecenas pulvinar lobortis est phasellus sit');
insert into examples (text) values ('feugiat non pretium quis lectus suspendisse potenti in eleifend quam');
insert into examples (text) values ('nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum');
insert into examples (text) values ('nisl nunc nisl duis bibendum felis sed');
insert into examples (text) values ('sed magna at nunc commodo');
insert into examples (text) values ('aenean lectus pellentesque eget nunc donec quis orci');
insert into examples (text) values ('placerat praesent blandit nam nulla integer pede justo');
insert into examples (text) values ('dui vel nisl duis ac');
insert into examples (text) values ('varius integer ac leo pellentesque ultrices mattis odio donec');
insert into examples (text) values ('bibendum imperdiet nullam orci pede venenatis');
insert into examples (text) values ('venenatis tristique fusce congue diam id ornare imperdiet sapien urna');
insert into examples (text) values ('nunc purus phasellus in felis donec semper sapien');
insert into examples (text) values ('blandit mi in porttitor pede justo eu');