insert into definitions (text) values ('nulla quisque arcu libero rutrum ac lobortis vel dapibus at');
insert into definitions (text) values ('mi pede malesuada in imperdiet et commodo vulputate');
insert into definitions (text) values ('purus aliquet at feugiat non pretium quis');
insert into definitions (text) values ('et commodo vulputate justo in blandit');
insert into definitions (text) values ('ultrices posuere cubilia curae duis faucibus accumsan odio');
insert into definitions (text) values ('risus praesent lectus vestibulum quam sapien varius ut blandit non');
insert into definitions (text) values ('parturient montes nascetur ridiculus mus vivamus');
insert into definitions (text) values ('amet sapien dignissim vestibulum vestibulum ante');
insert into definitions (text) values ('fringilla rhoncus mauris enim leo rhoncus');
insert into definitions (text) values ('sit amet lobortis sapien sapien non');
insert into definitions (text) values ('augue vestibulum rutrum rutrum neque aenean auctor');
insert into definitions (text) values ('cubilia curae duis faucibus accumsan odio curabitur convallis duis');
insert into definitions (text) values ('lacus at turpis donec posuere metus vitae ipsum aliquam');
insert into definitions (text) values ('nec sem duis aliquam convallis nunc');
insert into definitions (text) values ('quam nec dui luctus rutrum nulla tellus in');
insert into definitions (text) values ('rutrum rutrum neque aenean auctor gravida sem praesent id');
insert into definitions (text) values ('turpis eget elit sodales scelerisque mauris sit amet eros suspendisse');
insert into definitions (text) values ('sem praesent id massa id nisl venenatis lacinia aenean');
insert into definitions (text) values ('dignissim vestibulum vestibulum ante ipsum primis in faucibus orci');
insert into definitions (text) values ('gravida sem praesent id massa id nisl venenatis lacinia');
insert into definitions (text) values ('massa quis augue luctus tincidunt nulla');
insert into definitions (text) values ('nunc commodo placerat praesent blandit nam');
insert into definitions (text) values ('vehicula condimentum curabitur in libero ut massa volutpat convallis');
insert into definitions (text) values ('praesent blandit lacinia erat vestibulum sed magna at');
insert into definitions (text) values ('nisl duis bibendum felis sed interdum venenatis turpis enim');